CREATE TABLE public.words (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  word TEXT NOT NULL,
  meaning TEXT NOT NULL,
  part_of_speech TEXT NOT NULL,
  difficulty INTEGER NOT NULL,
  attack INTEGER NOT NULL,
  defense INTEGER NOT NULL,
  mana_cost INTEGER NOT NULL,
  CONSTRAINT words_pkey PRIMARY KEY (id)
);

ALTER TABLE public.words ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read access for all users" ON public.words FOR SELECT USING (TRUE);


